table ab_test_summary
	lineageTag: 8fb11229-6d51-4664-9d90-8220dfba9640

	measure 'Absolute Lift Display' = FORMAT(MAX(ab_test_summary[absolute_lift]) * 100, "+0.00;-0.00") & " pp"
		lineageTag: 38aa64b6-8ad0-433a-bc7a-84f4a6367f49

	measure 'Relative Lift Display' = FORMAT(MAX(ab_test_summary[relative_lift]), "+0.00%;-0.00%")
		lineageTag: 5569c8ca-339c-493d-adfd-0809bee5b5f0

	measure 'Incremental Revenue per Billing Session' = MAX(ab_test_summary[revenue_per_billing_session_difference])
		formatString: +$0.00;-$0.00
		lineageTag: c48d2d55-e421-40e0-b51d-1782422e9255

	measure 'P-value Display' = IF(MAX(ab_test_summary[p_value]) < 0.001, "< 0.001", FORMAT(MAX(ab_test_summary[p_value]), "0.000"))
		lineageTag: 47ad12f1-c7d2-4c3a-876d-d45960c43ec8

	measure '95% CI Display' = FORMAT(MAX(ab_test_summary[ci_lower]) * 100, "+0.00;-0.00") & " pp ～ " & FORMAT(MAX(ab_test_summary[ci_upper]) * 100, "+0.00;-0.00") & " pp"
		lineageTag: 212bf409-0d46-4d2f-a59a-3029053bd721

	measure 'Refund Difference Display' = FORMAT(MAX(ab_test_summary[refund_rate_difference]) * 100, "+0.00;-0.00") & " pp"
		lineageTag: a645300a-26ef-494e-b3ee-3e6ec4f435c4

	column billing_version
		dataType: string
		lineageTag: 21a05aeb-ce34-4859-b9ec-3cbe64a607c2
		summarizeBy: none
		sourceColumn: billing_version

		annotation SummarizationSetBy = Automatic

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: dc9753d1-64a7-43ad-92c3-80448c97790f
		summarizeBy: sum
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column purchasing_sessions
		dataType: int64
		formatString: 0
		lineageTag: 51d1b4ef-5905-4c4b-994d-822168046038
		summarizeBy: sum
		sourceColumn: purchasing_sessions

		annotation SummarizationSetBy = Automatic

	column purchase_conversion_rate
		dataType: double
		lineageTag: 77648a0a-5b2f-4f0f-a0e3-d496b31f3aa8
		summarizeBy: sum
		sourceColumn: purchase_conversion_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue
		dataType: double
		lineageTag: 5b8fb751-d54a-4ddb-ad40-e6b703a8c5f6
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue_per_billing_session
		dataType: double
		lineageTag: c466e7fc-5652-4111-8046-96f99cee9771
		summarizeBy: sum
		sourceColumn: revenue_per_billing_session

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column orders
		dataType: int64
		formatString: 0
		lineageTag: dd3ea1e6-4237-4e92-a683-979fbd465d6b
		summarizeBy: sum
		sourceColumn: orders

		annotation SummarizationSetBy = Automatic

	column refunded_orders
		dataType: int64
		formatString: 0
		lineageTag: ca4bddc6-ef49-430a-8410-a0039c75abac
		summarizeBy: sum
		sourceColumn: refunded_orders

		annotation SummarizationSetBy = Automatic

	column refund_rate
		dataType: double
		lineageTag: 4f222c78-cc1e-4574-972c-fe3180de5963
		summarizeBy: sum
		sourceColumn: refund_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column absolute_lift
		dataType: double
		lineageTag: 7d8986b0-476b-4895-acc2-c73ad627c409
		summarizeBy: sum
		sourceColumn: absolute_lift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column relative_lift
		dataType: double
		lineageTag: 4697f459-512f-4d11-89a8-96336bf44822
		summarizeBy: sum
		sourceColumn: relative_lift

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue_per_billing_session_difference
		dataType: double
		lineageTag: 3545002a-b3a4-4884-8a3e-621698d6e5dd
		summarizeBy: sum
		sourceColumn: revenue_per_billing_session_difference

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column z_statistic
		dataType: double
		lineageTag: 3755e76c-0b6e-407d-a6c8-80e14cffc35b
		summarizeBy: sum
		sourceColumn: z_statistic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column p_value
		dataType: double
		lineageTag: 752512c0-2241-44d9-ad30-efa77b93f1ef
		summarizeBy: sum
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ci_lower
		dataType: double
		lineageTag: 8071f802-da6d-4b09-87c5-be052cfdb4e1
		summarizeBy: sum
		sourceColumn: ci_lower

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ci_upper
		dataType: double
		lineageTag: b78ccbc3-03b5-4e4c-8f65-6c424189e5bb
		summarizeBy: sum
		sourceColumn: ci_upper

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column srm_p_value
		dataType: double
		lineageTag: cb9bfe7b-f804-4d82-a90a-0e78fe79368c
		summarizeBy: sum
		sourceColumn: srm_p_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column refund_rate_difference
		dataType: double
		lineageTag: 7c063990-a9c6-4a05-ace6-c9e1a323318b
		summarizeBy: sum
		sourceColumn: refund_rate_difference

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column refund_z_statistic
		dataType: double
		lineageTag: 1cd6abc3-baab-414c-ad90-3704a74c0c0c
		summarizeBy: sum
		sourceColumn: refund_z_statistic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column refund_p_value
		dataType: double
		lineageTag: 95de4011-a2f2-43eb-9229-75137b1a6ef0
		summarizeBy: sum
		sourceColumn: refund_p_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column billing_version_cn = SWITCH(ab_test_summary[billing_version], "control", "对照组", "treatment", "实验组")
		dataType: string
		lineageTag: 197dff7b-623c-4014-ac46-368eac4cc7b0
		summarizeBy: none
		sortByColumn: billing_version_sort

	column billing_version_sort = SWITCH(ab_test_summary[billing_version], "control", 1, "treatment", 2)
		dataType: int64
		formatString: 0
		lineageTag: 78c06c01-ad32-45b6-b633-29fd44377d60
		summarizeBy: none

	partition ab_test_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrator\Desktop\maven_ecommerce_ab\output\tables\ab_test_summary.csv"),[Delimiter=",", Columns=20, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"billing_version", type text}, {"sessions", Int64.Type}, {"purchasing_sessions", Int64.Type}, {"purchase_conversion_rate", type number}, {"revenue", type number}, {"revenue_per_billing_session", type number}, {"orders", Int64.Type}, {"refunded_orders", Int64.Type}, {"refund_rate", type number}, {"absolute_lift", type number}, {"relative_lift", type number}, {"revenue_per_billing_session_difference", type number}, {"z_statistic", type number}, {"p_value", type number}, {"ci_lower", type number}, {"ci_upper", type number}, {"srm_p_value", type number}, {"refund_rate_difference", type number}, {"refund_z_statistic", type number}, {"refund_p_value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

