table experiment_diagnostic_metrics
	lineageTag: 00000000-0000-0000-0000-383062404348

	measure 'Billing Abandonment Rate' = MAX(experiment_diagnostic_metrics[billing_abandonment_rate])
		formatString: 0.00%
		lineageTag: d27b9afd-a0df-4b36-96a9-25913dc7432b

	column billing_version
		dataType: string
		lineageTag: 3566e79d-9118-4f6d-932f-af129065880a
		summarizeBy: none
		sourceColumn: billing_version

	column sessions
		dataType: int64
		formatString: #,0
		lineageTag: ce71ec0f-2816-4639-9de6-377f6107ee76
		summarizeBy: none
		sourceColumn: sessions

	column purchases
		dataType: int64
		formatString: #,0
		lineageTag: 534f0113-b902-424a-aad9-c53dd5cbd503
		summarizeBy: none
		sourceColumn: purchases

	column billing_abandonment_rate
		dataType: double
		formatString: 0.00%
		lineageTag: 4954ae68-d9c2-4e20-80d0-21c14263a952
		summarizeBy: none
		sourceColumn: billing_abandonment_rate

	partition experiment_diagnostic_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\Users\\Administrator\\Desktop\\maven_ecommerce_ab\\output\\tables\\experiment_diagnostic_metrics.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"billing_version", type text}, {"sessions", Int64.Type}, {"purchases", Int64.Type}, {"billing_abandonment_rate", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

