table funnel_metrics
	lineageTag: 5a9c9e28-c9a5-46ef-bd75-7d06ae48b791

	column step_number
		dataType: int64
		formatString: 0
		lineageTag: e5c2ef7a-b1e6-4737-9b2d-e69dc45e78f3
		summarizeBy: sum
		sourceColumn: step_number

		annotation SummarizationSetBy = Automatic

	column funnel_stage
		dataType: string
		lineageTag: ce9a0de5-3dae-4d29-b108-8266bc1d39fe
		summarizeBy: none
		sourceColumn: funnel_stage
		sortByColumn: step_number

		annotation SummarizationSetBy = Automatic

	column pageview_url
		dataType: string
		lineageTag: 1642d174-92d5-425f-9f67-c656879e8f5b
		summarizeBy: none
		sourceColumn: pageview_url

		annotation SummarizationSetBy = Automatic

	column reached_sessions
		dataType: int64
		formatString: 0
		lineageTag: 323c9fbc-c8df-40c7-9e8c-012d778af1dc
		summarizeBy: sum
		sourceColumn: reached_sessions

		annotation SummarizationSetBy = Automatic

	column step_conversion_rate
		dataType: double
		lineageTag: 3de24270-29fd-4465-8b88-e271e3c1f925
		summarizeBy: sum
		sourceColumn: step_conversion_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column drop_off_rate
		dataType: double
		lineageTag: 5b2f462d-77a7-4fc7-bb77-271a0552ea6b
		summarizeBy: sum
		sourceColumn: drop_off_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column funnel_stage_cn = SWITCH(funnel_metrics[step_number], 1, "落地页", 2, "商品列表", 3, "商品详情", 4, "购物车", 5, "配送", 6, "结算", 7, "购买")
		dataType: string
		lineageTag: 8fad7b93-229a-43e1-a7e7-d980c6786793
		summarizeBy: none
		sortByColumn: step_number

	column step_transition_cn = SWITCH(funnel_metrics[step_number], 1, BLANK(), 2, "落地页 → 商品列表", 3, "商品列表 → 商品详情", 4, "商品详情 → 购物车", 5, "购物车 → 配送", 6, "配送 → 结算", 7, "结算 → 购买")
		dataType: string
		lineageTag: bf42406b-c67a-4eae-8d7b-698c6ec037e5
		summarizeBy: none
		sortByColumn: step_number

	partition funnel_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrator\Desktop\maven_ecommerce_ab\output\tables\funnel_metrics.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"step_number", Int64.Type}, {"funnel_stage", type text}, {"pageview_url", type text}, {"reached_sessions", Int64.Type}, {"step_conversion_rate", type number}, {"drop_off_rate", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

