table overall_metrics
	lineageTag: 35558c39-441a-474e-81e0-8aa6507dc226

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: 59e86c8a-90be-40bf-946d-980ecf997e29
		summarizeBy: sum
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column users
		dataType: int64
		formatString: 0
		lineageTag: a9230653-e56a-4930-a3fe-6df1ad39dc8d
		summarizeBy: sum
		sourceColumn: users

		annotation SummarizationSetBy = Automatic

	column orders
		dataType: int64
		formatString: 0
		lineageTag: eef31a8d-a274-4a2f-b220-b81fa773a6e7
		summarizeBy: sum
		sourceColumn: orders

		annotation SummarizationSetBy = Automatic

	column purchase_conversion_rate
		dataType: double
		lineageTag: 96aec169-743a-4c5f-ad62-9e497a26408a
		summarizeBy: sum
		sourceColumn: purchase_conversion_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue
		dataType: double
		lineageTag: bd11f94a-c781-4d4e-bb66-96c0e2cb248c
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue_per_session
		dataType: double
		lineageTag: 0e0051f6-d796-4039-80a7-4b2f917982fb
		summarizeBy: sum
		sourceColumn: revenue_per_session

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aov
		dataType: double
		lineageTag: 698120e0-a3ae-414a-b980-bb6ad60e722d
		summarizeBy: sum
		sourceColumn: aov

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition overall_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrator\Desktop\maven_ecommerce_ab\output\tables\overall_metrics.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sessions", Int64.Type}, {"users", Int64.Type}, {"orders", Int64.Type}, {"purchase_conversion_rate", type number}, {"revenue", type number}, {"revenue_per_session", type number}, {"aov", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

