table quarterly_metrics
	lineageTag: 584bc213-4dd7-405b-93e7-8a981cfbab93

	column quarter_start
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 32ce76e8-3cee-4ea8-b2d9-91e489be5a8a
		summarizeBy: none
		sourceColumn: quarter_start

	column year_quarter
		dataType: string
		lineageTag: 8012b623-4c53-4554-929b-850098caa814
		summarizeBy: none
		sourceColumn: year_quarter
		sortByColumn: quarter_start

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: 22552c8d-4fc7-4559-9863-87401115474b
		summarizeBy: sum
		sourceColumn: sessions

	column purchasing_sessions
		dataType: int64
		formatString: 0
		lineageTag: f50dc18b-afe6-46b1-9b1c-73c00fdfee83
		summarizeBy: sum
		sourceColumn: purchasing_sessions

	column orders
		dataType: int64
		formatString: 0
		lineageTag: 019a3882-84cc-4119-8597-7a0fa08f71dc
		summarizeBy: sum
		sourceColumn: orders

	column purchase_conversion_rate
		dataType: double
		formatString: 0.00%
		lineageTag: 9d3194fc-7275-4b2d-af4a-85d2125fa032
		summarizeBy: sum
		sourceColumn: purchase_conversion_rate

	column revenue
		dataType: double
		formatString: $#,##0.00
		lineageTag: 8306cca0-5801-49d6-b407-eee1c35e8091
		summarizeBy: sum
		sourceColumn: revenue

	column revenue_per_session
		dataType: double
		formatString: $#,##0.00
		lineageTag: b92ee46e-0d26-455a-ab73-d1c7a966221c
		summarizeBy: sum
		sourceColumn: revenue_per_session

	partition quarterly_metrics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrator\Desktop\maven_ecommerce_ab\output\tables\quarterly_metrics.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"quarter_start", type date}, {"year_quarter", type text}, {"sessions", Int64.Type}, {"purchasing_sessions", Int64.Type}, {"orders", Int64.Type}, {"purchase_conversion_rate", type number}, {"revenue", type number}, {"revenue_per_session", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
